### ISSUE TITLE
rows get missing when multiple pages are fetched

### ISSUE THREAD

**Issue by nfssdq** [segmentio/go-athena#12]
Hi,

We recently tried to use your awesome project on Athena, but during testing we found some data is not returned. Upon investigating i found that whenever fetchNextPage is called, it skips the first row assuming it is a header, which is true for the first page only. The subsequent pages don't have this, so the first row gets missed. I hope you guys can take a look into this matter.

**Comment by tejasmanohar** [comment]
Nice find!

Could you send a PR with the fix and a test that has multiple pages, @nfssdq? There's another bug in this section of the code, too (https://github.com/segmentio/go-athena/pull/10), if you'd like to tackle it at the same time.
